name: Deploy
on: 
  push:
    branches:
      - master
          
jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: '12.x'
    - name: npm install
    - name: npm build
    - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./website.zip ./build
    - name: Push Zip To Server
      run: |
        curl --request POST \
        --url https://docs.alphaTab.net/deploy.php \
        --header 'authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}' \
        --header 'branch: website' \
        --data "website=@website.zip"
